@startuml 
start 
title СА: Замена плейсход

:Нач. установ.; 
    note right
        Инициализ. МП
    end note
:Прочесть документ;
repeat
  :Выбрать ПЛ;
  if (ПЛ валид?) then (Да)
    :Найти знач.;
    :Заменить ПЛ;
  else (Нет)
    :Пропустить ПЛ;
  endif
repeat while (ПЛ есть?)
:Обновить документ;
stop
@enduml
