@startuml
start
title "Сканирование"
:Начальные установ.;
:Открыть файл;
:Определить тип;
if (DOCX?) then (Да)
  :Читать Word;
  :Искать {{текст}};
  :Формировать МП;
else (Нет)
  if (XLSX?) then (Да)
    :Читать Excel;
    :Искать {{текст}};
    :Формировать МП;
  else (Нет)
    :Выдать ошибку;
  endif
endif
:Вернуть МП;
stop
@enduml
