@startuml
start

:Начальные установ.;
note right
путь шаблона (ПШ), тип шаблона (ТП) и массив плейсхолдеров (МП).
end note
:Выбрать шаблон;
if (Шаблон есть?) then (Да)
  :Сохранить ПШ;
  :Определить тип;
  if (DOCX?) then (Да)
    :Установить DOCX;
  else (Нет)
    :Установить XLSX;
  endif
  :Сканировать шаблон;
  :Формировать МП;
      note right
      массив плейсхолдеров (МП), 
      где для каждого поля задаётся 
      имя, тип 
      (например, Numeric или String) 
      и описание. 
      end note
  :Отобразить МП; 
      note right
        Вывести на экран в виде таблицы
      end note
  :Ограничить ввод данных;
  :Ввести данные; 
    note right
        Ввод от Пользователя
    end note
  if (Данные введены корректно?) then (нет)
    :Вывести сообщение об ошибке;
  else (да)
      :Зам. плейсхолдеры;
      :Сформировать документ;
      if (Сохранить?) then (Да)
        :Сохранить файл;
      else (Нет)
        if (Отправить?) then (Да)
          :Ввести email;
          :Отправить файл;
        endif
      endif
      endif
else
  :Отмена шаблона;
endif

:Сохранить логи;
stop
@enduml
